/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER-A514
 */
public class FrameDiskon extends javax.swing.JFrame {

    /**
     * Creates new form FrameDiskon
     */
    public FrameDiskon() {
        initComponents();
        
        txtRiwayat.setEditable(false);     // Tidak bisa diketik/diedit
        txtRiwayat.setFocusable(false);    // Tidak bisa diklik / tidak bisa dapat fokus

        txtHargaAkhir.setEditable(false);     // Tidak bisa diketik/diedit
        txtHargaAkhir.setFocusable(false);
        
        cmbDiskon.addItem("5%");
        cmbDiskon.addItem("10%");
        cmbDiskon.addItem("15%");
        cmbDiskon.addItem("20%");
        cmbDiskon.addItem("25%");
        cmbDiskon.addItem("30%");
        cmbDiskon.addItem("35%");
        cmbDiskon.addItem("40%");
        cmbDiskon.addItem("45%");
        cmbDiskon.addItem("50%");

        // Atur nilai awal slider (0–50%)
        sldDiskon.setMinimum(0);
        sldDiskon.setMaximum(50);
        sldDiskon.setMajorTickSpacing(10);
        sldDiskon.setPaintTicks(true);
        sldDiskon.setPaintLabels(true);
        
        cmbDiskon.addActionListener(e -> {
            int selectedDiskon = Integer.parseInt(cmbDiskon.getSelectedItem().toString().replace("%", ""));
            sldDiskon.setValue(selectedDiskon);
        });
        
        // Set tampilan awal label sesuai posisi slider
        lblNilaiSlider.setText(sldDiskon.getValue() + "%");

        // Sinkronisasi Slider -> ComboBox
        // Event listener saat slider digeser
        sldDiskon.addChangeListener(e -> {
            int nilai = sldDiskon.getValue();
            lblNilaiSlider.setText(nilai + "%"); // ubah label sesuai nilai slider

            // Sinkronkan combo box ke slider jika nilainya cocok
            for (int i = 0; i < cmbDiskon.getItemCount(); i++) {
                int valCombo = Integer.parseInt(cmbDiskon.getItemAt(i).replace("%", ""));
                if (valCombo == nilai) {
                    cmbDiskon.setSelectedIndex(i);
                    break;
                }
            }
        });

        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRiwayat = new javax.swing.JTextArea();
        txtHargaAsli = new javax.swing.JTextField();
        txtKupon = new javax.swing.JTextField();
        cmbDiskon = new javax.swing.JComboBox<>();
        jlabel = new javax.swing.JLabel();
        sldDiskon = new javax.swing.JSlider();
        txtHargaAkhir = new javax.swing.JTextField();
        lblNilaiSlider = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Perhitungan Diskon");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Harga Asli");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Pilih Diskon (%)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Kode Kupon");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Hasil Akhir");

        btnHitung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Riwayat Perhitungan");

        txtRiwayat.setColumns(20);
        txtRiwayat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRiwayat.setRows(5);
        jScrollPane1.setViewportView(txtRiwayat);

        txtHargaAsli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHargaAsli.setPreferredSize(new java.awt.Dimension(150, 26));

        txtKupon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKupon.setPreferredSize(new java.awt.Dimension(150, 26));
        txtKupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKuponActionPerformed(evt);
            }
        });

        cmbDiskon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlabel.setText("Atau Gunakan Slider");

        sldDiskon.setMajorTickSpacing(10);
        sldDiskon.setMaximum(50);
        sldDiskon.setMaximumSize(new java.awt.Dimension(200, 30));
        sldDiskon.setMinimumSize(new java.awt.Dimension(200, 30));
        sldDiskon.setPreferredSize(new java.awt.Dimension(200, 30));
        sldDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDiskonStateChanged(evt);
            }
        });

        txtHargaAkhir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHargaAkhir.setPreferredSize(new java.awt.Dimension(150, 26));

        lblNilaiSlider.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNilaiSlider.setText("0%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDiskon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHargaAsli, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jlabel)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(sldDiskon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKupon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHargaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNilaiSlider))
                    .addComponent(jScrollPane1))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtHargaAsli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel)
                    .addComponent(sldDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNilaiSlider))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHargaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKuponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKuponActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            double hargaAsli = Double.parseDouble(txtHargaAsli.getText());
            int diskonPersen = Integer.parseInt(cmbDiskon.getSelectedItem().toString().replace("%", ""));
            int diskonSlider = sldDiskon.getValue();

            // Ambil diskon maksimum (antara combobox dan slider)
            int diskonFinal = Math.max(diskonPersen, diskonSlider);

            // Tambahan diskon jika pakai kode kupon
            String kupon = txtKupon.getText().trim();
            if (kupon.equalsIgnoreCase("HEMAT5")) {
                diskonFinal += 5;
            } else if (kupon.equalsIgnoreCase("SUPER10")) {
                diskonFinal += 10;
            }

            // Batas maksimum 70%
            if (diskonFinal > 70) diskonFinal = 70;

            double jumlahDiskon = hargaAsli * diskonFinal / 100;
            double hargaAkhir = hargaAsli - jumlahDiskon;

            txtHargaAkhir.setText(String.format("Rp %.2f", hargaAkhir));

            // Tambahkan ke riwayat
            txtRiwayat.append("Harga: Rp" + hargaAsli +
                " | Diskon: " + diskonFinal + "% | Hemat: Rp" + jumlahDiskon + "\n");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan harga asli dengan benar!");
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtHargaAsli.setText("");
        txtKupon.setText("");
        txtHargaAkhir.setText("");
        sldDiskon.setValue(0);
        cmbDiskon.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void sldDiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDiskonStateChanged
//        jlabel.setText(sldDiskon.getValue() + "%");
    }//GEN-LAST:event_sldDiskonStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDiskon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel lblNilaiSlider;
    private javax.swing.JSlider sldDiskon;
    private javax.swing.JTextField txtHargaAkhir;
    private javax.swing.JTextField txtHargaAsli;
    private javax.swing.JTextField txtKupon;
    private javax.swing.JTextArea txtRiwayat;
    // End of variables declaration//GEN-END:variables
}
